DoKnow.CloudEdu.CMS.Host/Models/PageHeader.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DoKnow.CloudEdu.CMS.Host.Models
{
    public class PageHeader
    {
        public string Title { get; set; }
        public Dictionary<string, string> Urls { get; set; }
    }
}

DoKnow.CloudEdu.CMS.Host/Controllers/BsUserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DoKnow.CloudEdu.CMS.Host.Models;
using DoKnow.CloudEdu.Common.Attrs;
using DoKnow.CloudEdu.Common.Consts;
using DoKnow.CloudEdu.Common.Enums;
using DoKnow.CloudEdu.DataContract.Model.Base;
using DoKnow.Common.Utility;
using DoKnow.Common.Utility.EnDe;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Webdiyer.WebControls.Mvc;

namespace DoKnow.CloudEdu.CMS.Host.Controllers
{
    public class BsUserController : BaseController
    {
        //
        // GET: /BsUser/

        public ActionResult Index(BSUserPageInfo request)
        {
            if (null != TempData["Msg"])
            {
                ViewBag.Msg = TempData["Msg"].ToString();
            }
            return QueryByUser(request);
        }
        [MenuItem("~/BsUser/Index")]
        public ActionResult QueryByUser(BSUserPageInfo request)
        {
            UserDatas users = HttpHelper.Post<UserDatas>(Server + ServicePath.UserRead,
                JsonConvert.SerializeObject(
                new
                {
                    ActionName = "RetrieveUsers",
                    Pars = 
                      new {
                          user = EmitHelper.Map<BSUserPageInfo,BSUserInfo>(request),
                          page = EmitHelper.Map<BSUserPageInfo, PageInfo>(request)
                          } 
                }));
            if(null != users && null != users.UserEntitys && users.UserEntitys.Count >0)
            {
                var model = new PagedList<BSUserPageInfo>(EmitHelper.Map<BSUserInfo,BSUserPageInfo>(users.UserEntitys), request.PageIndex, request.PageSize, users.Total);
                return View("Index", model);
            }
            return View("Index"); 
        }
        [MenuItem("~/BsUser/Index")]
        public ActionResult Add()
        {
            if (null != TempData["Msg"])
            {
                ViewBag.Msg = TempData["Msg"].ToString();
            }
            ViewBag.ComStatus = EnumHelper.GetSelectList<EnumHelper.CommonStatus>();
            return View("Add", new BSUserInfo());
        }
        [MenuItem("~/BsUser/Index")]
        public ActionResult AddSave(BSUserInfo model)
        {
            //var managerClient = new BsUserManagerClient();
            model.Creator = model.Modifier = CurrentUser.UserEntity.Code;
            model.CreateTime = model.ModifyTime = System.DateTime.Now;
            //model.STATUS = (int)EnumHelper.CommonStatus.Active;
            var response = HttpHelper.Post(Server + ServicePath.UserRead,
                    JsonConvert.SerializeObject(
                    new
                    {
                        ActionName = "CreateUser",
                        Pars =
                          new
                          {
                              user = model
                          }
                    }, new IsoDateTimeConverter() { DateTimeFormat = "yyyy-MM-dd HH:mm:ss" }));
            if (!response.IsSuccess)
            {
                ViewBag.ComStatus = EnumHelper.GetSelectList<EnumHelper.CommonStatus>(model.Status.ToString());
                ViewBag.ErrMsg = string.IsNullOrEmpty(response.ErrMsg) ? string.Empty : (response.ErrMsg + ",") + "新增失败！";
                return View("Add", model);
            }
            else
            {
                TempData["Msg"] = "新增成功！";
                return RedirectToAction("Index");
            }
        }
        [MenuItem("~/BsUser/Index")]
        public ActionResult Edit(int id,string code,string mobile)
        {
            var model = HttpHelper.Post<BSUserInfo>(Server + ServicePath.UserRead,
                    JsonConvert.SerializeObject(
                    new
                    {
                        ActionName = "RetrieveUser",
                        Pars =
                          new
                          {
                              user = new BSUserInfo() { ID = id }
                          }
                    }));
            if (model != null)
            {
                ViewBag.ComStatus = EnumHelper.GetSelectList<EnumHelper.CommonStatus>(model.Status.ToString());
                return View("Edit", model);
            }
            else
            {
                TempData["Msg"] = "该用户已不存在！";
                return RedirectToAction("Index", new {Code=code,Mobile=mobile });
            }
        }
        [MenuItem("~/BsUser/Index")]
        public ActionResult EditSave(BSUserInfo model)
        {
            //var managerClient = new BsUserManagerClient();
            model.Modifier = CurrentUser.UserEntity.Code;
            model.ModifyTime = System.DateTime.Now;
            //model.STATUS = (int)EnumHelper.CommonStatus.Active;
            var response = HttpHelper.Post(Server + ServicePath.UserRead,
                    JsonConvert.SerializeObject(
                    new
                    {
                        ActionName = "UpdateUser",
                        Pars =
                          new
                          {
                              user = model
                          }
                    }, new IsoDateTimeConverter() { DateTimeFormat = "yyyy-MM-dd HH:mm:ss" }));
            if (!response.IsSuccess)
            {
                ViewBag.ErrMsg = string.IsNullOrEmpty(response.ErrMsg) ? string.Empty : (response.ErrMsg + ",") + "编辑失败！";
                ViewBag.ComStatus = EnumHelper.GetSelectList<EnumHelper.CommonStatus>(model.Status.ToString());
                return View("Edit", model);
            }
            else
            {
                TempData["Msg"] = "编辑成功！";
                return RedirectToAction("Index");
            }
        }

        [MenuItem("~/BsUser/Index")]
        public ActionResult Delete(int id)
        {
            var response = HttpHelper.Post(Server + ServicePath.UserWrite,
                JsonConvert.SerializeObject(
                new
                {
                    ActionName = "DeleteUser",
                    Pars =
                      new
                      {
                          ID = id
                      }
                }));
            if (response.IsSuccess)
            {
                TempData["Msg"] = "删除成功！";
                return RedirectToAction("Index");
            }
            else
            {
                TempData["Msg"] = string.IsNullOrEmpty(response.ErrMsg)?string.Empty:(response.ErrMsg+",")+"删除失败！";
                return RedirectToAction("Index");
            }
        }
        [MenuItem("~/Home/Index")]
        public ActionResult ChangePWD()
        {
            PwdModel model = new PwdModel();
            model.ID = CurrentUser.UserEntity.ID;
            model.Name = CurrentUser.UserEntity.RealName;
            return View("ChangePWD", model);
        }
        [HttpPost]
        public ActionResult ChangePWD(PwdModel mode)
        {
            if (mode.NewPWD != mode.ConfirmPWD)
            {
                ViewBag.ErrMsg = "新密码与确认新密码不一致！";
                return View("ChangePWD", mode);
            }
            var response = HttpHelper.Post(Server + ServicePath.UserRead,
                JsonConvert.SerializeObject(
                new
                {
                    ActionName = "UpdatePassword",
                    Pars =
                    new
                    {
                        userID = CurrentUser.UserEntity.ID,
                        oldPassword = mode.OldPWD,
                        newPassword = mode.NewPWD
                    }
                }));
            if(response.IsSuccess)
            {
                Request.Cookies.Remove(CookiesKey.LoginToken);
                return RedirectToAction("Login", "Home");
            }
            else
            {
                ViewBag.ErrMsg = response.ErrMsg+"原始密码不正确"; 
                return View(mode);
            }
        }
        public ActionResult GetUserCategroy()
        {
            var categorys = EnumHelper.GetList(typeof(EnumHelper.UserCategory));
            var result = Json(categorys);
            return result;
        }
    }
}

DoKnow.CloudEdu.CMS.Host/Controllers/SharedController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DoKnow.CloudEdu.CMS.Host.Models;

namespace DoKnow.CloudEdu.CMS.Host.Controllers
{
    public class SharedController : BaseController
    {
        //
        // GET: /Shared/

        public ActionResult Index()
        {
            return View();
        }
        [ChildActionOnly]
        public ActionResult _TopNavMenu()
        {
            //ViewBag.PageSize = PageSize;
            return PartialView();
        }
        [ChildActionOnly]
        public ActionResult _LeftNavMenu()
        {
            if (null != CurrentUser.UserRoles && CurrentUser.UserRoles.Count > 0)
            {
                var roleIds = CurrentUser.UserRoles.Select(i => i.RoleID).Distinct();
                #if DEBUG
                var modules = CurCache.BSModuleFull;
                #else
                var moduleIds = CurCache.BSRoleModuleFull.Where(o => roleIds.Contains(o.RoleID)).Select(o => o.ModuleID).Distinct();
                var modules = CurCache.BSModuleFull.Where(o => moduleIds.Contains(o.ID)).ToList();
                var parentModuleIds = modules.Select(o => o.ParentID).Distinct();
                modules = CurCache.BSModuleFull.Where(i => parentModuleIds.Contains(i.ID)).Concat(modules).ToList();
                #endif
                var pagePath = HttpContext.Items[Request_Path_Item_Key] as string;
                var menuItemPath = HttpContext.Items[Menu_Path_Item_Key] as string;
                var model = new List<MenuItemModel>();
                foreach (var item in modules.Where(o => o.ParentID == 0).OrderBy(o => o.ModuleOrder))
                {
                    var node = new MenuItemModel()
                    {
                        Children = modules.Where(o => o.ParentID == item.ID).OrderBy(o => o.ModuleOrder).Select(o =>
                            new MenuItemModel
                            {
                                Children = null,
                                IconClass = null,
                                ID = o.ID,
                                IsActive = o.ModuleUrl.ToLower().IndexOf(pagePath) == 0,
                                Text = o.ModuleName,
                                Url = o.ModuleUrl
                            }).ToList(),
                        IconClass = item.ModuleIcon,
                        ID = item.ID,
                        IsActive = item.ModuleUrl.ToLower().IndexOf(pagePath) == 0,
                        Text = item.ModuleName,
                        Url = item.ModuleUrl
                    };

                    if (node.Children.Exists(o => o.IsActive))
                    {
                        node.IsActive = true;
                    }
                    else if (string.IsNullOrEmpty(menuItemPath) == false)
                    {
                        var activeItem = node.Children.FirstOrDefault(o => o.Url.ToLower().IndexOf(menuItemPath) == 0);
                        if (activeItem != null)
                        {
                            activeItem.IsActive = true;
                            node.IsActive = true;
                        }
                    }
                    model.Add(node);
                }
                return PartialView(model);
            }

            return PartialView();
            //return PartialView(menuList);
        }
    }
}

DoKnow.CloudEdu.CMS.Host/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="zh-cn" class="no-js">
<!--<![endif]-->
<!-- BEGIN HEAD -->
<head>
    <meta charset="utf-8" />
    <title>美邦C2MSCM</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta content="width=device-width, initial-scale=1.0" name="viewport" />
    <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
    <meta content="" name="description" />
    <meta content="" name="author" />
    <link href="~/assets/global/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
    <link href="~/assets/global/plugins/simple-line-icons/simple-line-icons.min.css" rel="stylesheet" />
    <link href="~/assets/global/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/assets/global/plugins/uniform/css/uniform.default.css" rel="stylesheet" />
    <link href="~/assets/global/plugins/bootstrap-switch/css/bootstrap-switch.min.css" rel="stylesheet" />
    <link href="~/Assets/global/Plugins/select2/select2.css" rel="stylesheet" />
    <link href="~/assets/global/plugins/jstree/dist/themes/default/style.min.css" rel="stylesheet" />
    <link href="~/assets/global/css/components.css" rel="stylesheet" />
    <link href="~/assets/global/css/plugins.css" rel="stylesheet" />
    <link href="~/assets/admin/layout/css/layout.css" rel="stylesheet" />
    <link href="~/assets/admin/layout/css/themes/default.css" rel="stylesheet" />
    <link href="~/assets/admin/layout/css/custom.css" rel="stylesheet" />
    <script src="~/assets/global/plugins/jquery-1.10.1.min.js"></script>
    @RenderSection("header", false)
</head>
<body class="page-header-fixed">
    <div class="page-header navbar navbar-fixed-top">
        <div class="page-header-inner">
            <div class="page-logo ">
                <a href="/">
                    <span class="text-logo">美邦C2MSCM</span>
                </a>
                <div class="menu-toggler sidebar-toggler hide">
                    <!-- DOC: Remove the above "hide" to enable the sidebar toggler button on header -->
                </div>
            </div>
            <a href="javascript:;" class="menu-toggler responsive-toggler" data-toggle="collapse" data-target=".navbar-collapse"></a>
            @Html.Action("_TopNavMenu", "Shared")
        </div>
    </div>
    <div class="clearfix"></div>
    <div class="page-container">
        @Html.Action("_LeftNavMenu", "Shared")
        <div class="page-content-wrapper">
            <div class="page-content" style="min-height: 572px;">
                @RenderBody()
            </div>
        </div>
    </div>

    <!-- END PAGE -->
    <!-- END CONTAINER -->
    <!-- BEGIN FOOTER -->

    <div class="page-footer">
        <div class="page-footer-inner">
            2015 &copy; Metersbonwe C2M Admin
        </div>
        <div class="scroll-to-top">
            <i class="icon-arrow-up"></i>
        </div>
    </div>
    <div tabindex="-1" class="modal fade in" id="contentLoading" role="basic" aria-hidden="false" style="display: block;">
        <img class="loading" alt="" src="~/Image/ajax-modal-loading.gif">
    </div>
    <div class="modal-backdrop fade in"></div>

    <!--[if lt IE 9]>
    <script src="/assets/global/plugins/respond.min.js"></script>
    <script src="/assets/global/plugins/excanvas.min.js"></script>
    <![endif]-->

    <script src="~/assets/global/plugins/jquery-migrate-1.2.1.min.js"></script>
    <script src="~/assets/global/plugins/jquery-ui/jquery-ui-1.10.3.custom.min.js"></script>
    <script src="~/assets/global/plugins/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/assets/global/plugins/bootstrap-hover-dropdown/bootstrap-hover-dropdown.min.js"></script>
    <script src="~/assets/global/plugins/jquery-slimscroll/jquery.slimscroll.min.js"></script>
    <script src="~/assets/global/plugins/jquery.blockui.min.js"></script>
    <script src="~/assets/global/plugins/jquery.cookie.min.js"></script>
    <script src="~/assets/global/plugins/uniform/jquery.uniform.min.js"></script>
    <script src="~/assets/global/plugins/bootstrap-switch/js/bootstrap-switch.min.js"></script>
    <script src="~/Assets/global/Plugins/select2/select2.min.js"></script>
    <script src="~/assets/global/scripts/metronic.js"></script>
    <script src="~/assets/admin/layout/scripts/layout.js"></script>
    <script src="~/Assets/global/Plugins/bootstrap-daterangepicker/moment.min.js"></script>
    <script src="~/Assets/global/Plugins/bootBox/bootbox.min.js"></script>
    <link href="~/Assets/global/Plugins/datatables/plugins/bootstrap/dataTables.bootstrap.css" rel="stylesheet" />
    <script src="~/Assets/global/Plugins/datatables/media/js/jquery.dataTables.js"></script>
    @*<script src="~/Assets/global/Scripts/datatable.js"></script>*@
    <script src="~/Assets/global/Plugins/datatables/extensions/TableTools/js/dataTables.tableTools.min.js"></script>
    <link href="~/Assets/global/Plugins/datatables/extensions/FixedColumns/css/dataTables.fixedColumns.min.css" rel="stylesheet" />
    <script src="~/Assets/global/Plugins/datatables/extensions/FixedColumns/js/dataTables.fixedColumns.js"></script>
    <script src="~/Assets/global/Plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js"></script>
    <script src="~/Assets/global/Scripts/dataTableExtention.js"></script>
    <script src="~/Assets/global/Plugins/jquery-bbq-1.2.1/jquery.ba-bbq.min.js"></script>
    <script src="~/Assets/global/Plugins/jquery-validation/jquery.validate.min.js"></script>
    <script src="~/Assets/global/Plugins/My97DatePicker/WdatePicker.js"></script>
    <script src="~/Scripts/pages/common.js"></script>
    @RenderSection("scripts", false)
    <script>
        jQuery(document).ready(function () {
            Metronic.init();
            Layout.init();
            if (window["pageReady"]) {
                window["pageReady"]();
            }
            $("#contentLoading,.modal-backdrop").remove();
            $(".sidebar-toggler").click(function () {
                var id = $("table.dataTable[id]").attr("id");
                $("#" + id).dataTable().fnDraw(false);
                //$("#" + id).DataTable().draw(false);
            });
            $(".disabledCutCopyPaste").bind("cut copy paste", function (e) {
                e.preventDefault();
            });
        });
    </script>
    <!-- END JAVASCRIPTS -->
</body>
<!-- END BODY -->

</html>

DoKnow.CloudEdu.CMS.Host/Views/Shared/_LeftNavMenu.cshtml
@model List<DoKnow.CloudEdu.CMS.Host.Models.MenuItemModel>
@{
    Layout = null;
}
<div class="page-sidebar-wrapper">
    <div class="page-sidebar navbar-collapse collapse">
        <!-- BEGIN SIDEBAR MENU -->
        <ul class="page-sidebar-menu " data-auto-scroll="true" data-slide-speed="200">
            <!-- DOC: To remove the sidebar toggler from the sidebar you just need to completely remove the below "sidebar-toggler-wrapper" LI element -->
            <li class="sidebar-toggler-wrapper">
                <!-- BEGIN SIDEBAR TOGGLER BUTTON -->
                <div class="sidebar-toggler">
                </div>
                <!-- END SIDEBAR TOGGLER BUTTON -->
            </li>
            <!-- BEGIN RESPONSIVE QUICK SEARCH FORM -->
            @*<form class="sidebar-search">
                    <div class="input-box">
                        <a href="javascript:;" class="remove"></a>
                        <input type="text" placeholder="Search..." />
                        <input type="button" class="submit" value=" " />
                    </div>
                </form>*@
            <!-- END RESPONSIVE QUICK SEARCH FORM -->
            @if( null != Model)
            {
                foreach (var node in Model)
            {
                <li class="@(node.IsActive?"active":"")">
                    <a href="@(string.IsNullOrEmpty(node.Url) ? "javascript:;" : node.Url)">
                        @if (!string.IsNullOrEmpty(node.IconClass))
                        {
                            <i class="@node.IconClass"></i>
                        }
                        <span class="title">@node.Text</span>
                        <span class="@(node.IsActive?"selected":"arrow ")"></span>
                    </a>
                    @if (node.Children.Count > 0)
                    {
                        <ul class="sub-menu">
                            @foreach (var item in node.Children)
                            {
                                <li class="@(item.IsActive ? "active" : "")">
                                    <a href="@item.Url">
                                        @if (!string.IsNullOrEmpty(item.IconClass))
                                        {
                                            <i class="icon-home"></i>
                                        }
                                        @item.Text
                                    </a>
                                </li>
                            }
                        </ul>
                    }
                </li>
            }
            }

        </ul>

        <!-- END SIDEBAR MENU -->
        <script type="text/javascript">
            function clickMenu(id) {
                localStorage.removeItem("startMenu");
                localStorage.setItem("startMenu", id);
                if (id == "home") {
                    $("#ulmenu li").removeClass("start active ");
                    $("#ulmenu li a span").get(1).className = "arrow";
                    $("#home").addClass("start active ");
                    $("#home a span").get(1).className = "selected";
                }
                else {
                    $("#home").removeClass("start active ");
                    $("#" + id).addClass("start active ");
                    $("#" + id + " a span").get(1).className = "selected";
                }
            }
        </script>
    </div>
</div>

DoKnow.CloudEdu.CMS.Host/Views/Shared/_PageHeader.cshtml
@model DoKnow.CloudEdu.CMS.Host.Models.PageHeader
<h3 class="page-title">
    @Model.Title
</h3>
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <i class="fa fa-home"></i>
            <a href="@Url.Action("Index", "Home")">首页</a>
            <i class="fa fa-angle-right"></i>
        </li>
        @foreach (string key in Model.Urls.Keys)
        {
            <li>
                <a href="@Model.Urls[key]">@key</a>
                <i class="fa fa-angle-right"></i>
            </li>
        }

    </ul>
</div>

DoKnow.CloudEdu.CMS.Host/Views/Shared/_TopNavMenu.cshtml
@using DoKnow.CloudEdu.CMS.Host.Models
@{
    Layout = null;
}
<input type="hidden" data-name="page_size" value="@ViewBag.PageSize" />
<div class="top-menu">
    <ul class="nav navbar-nav pull-right">
        <!-- BEGIN USER LOGIN DROPDOWN -->
        <li class="dropdown dropdown-user">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true" style="padding-top:13px;">
                @*@{
                        var url = "/assets/admin/layout/img/avatar3_small.jpg";
                        if (!string.IsNullOrEmpty(UserSession.Current.Title_Url))
                        {
                            url = UserSession.Current.Title_Url;
                        }
                    }
                    <img alt="" class="hide1 img-circle" src="@url" />*@
                <span class="username username-hide-on-mobile">
                    @CurSession.User.UserEntity.RealName
                </span>
                <i class="fa fa-angle-down"></i>
            </a>
            <ul class="dropdown-menu">
                <li>
                    <a href="@Url.Action("ChangePWD", "BsUser")">
                        <i class="icon-user"></i> 修改密码
                    </a>
                </li>
                @*<li style="display:none">
                        <a href="#">
                            <i class="icon-envelope-open"></i> 我的消息
                        </a>
                    </li>*@
                <li class="divider">
                </li>
                <li>
                    <a href="@Url.Action("Logout","Home",null)">
                        <i class="icon-key"></i> 退出系统
                    </a>
                </li>
            </ul>
        </li>
        <!-- END USER LOGIN DROPDOWN -->
        <!-- BEGIN QUICK SIDEBAR TOGGLER -->
        @*<li class="dropdown dropdown-quick-sidebar-toggler">
                <a href="@Url.Action("Logout","Account",null)" class="dropdown-toggle">
                    <i class="icon-logout"></i>
                </a>
            </li>*@
        <!-- END QUICK SIDEBAR TOGGLER -->
    </ul>
</div>