DoKnow.CloudEdu.CMS.Host/Controllers/AuthorityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DoKnow.CloudEdu.CMS.Host.Models;
using DoKnow.CloudEdu.Common.Attrs;
using DoKnow.CloudEdu.Common.Consts;
using DoKnow.CloudEdu.DataContract.Model.Base;
using DoKnow.Common.Utility;
using Newtonsoft.Json;
using Webdiyer.WebControls.Mvc;

namespace DoKnow.CloudEdu.CMS.Host.Controllers
{
    public class AuthorityController : BaseController
    {
        //
        // GET: /Authority/

        public ActionResult Index(BSRolePageInfo request)
        {
            return QueryBsRole(request);
        }
        public ActionResult QueryBsRole(BSRolePageInfo request)
        {
            RoleDatas roles = HttpHelper.Post<RoleDatas>(Server + ServicePath.RoleRead,
                JsonConvert.SerializeObject(
                new
                {
                    ActionName = "RetrieveRoles",
                    Pars =
                      new
                      {
                          role = EmitHelper.Map<BSRolePageInfo, BSRoleInfo>(request),
                          page = EmitHelper.Map<BSRolePageInfo, PageInfo>(request)
                      }
                }));
            if (null != roles && null != roles.RoleEntitys && roles.RoleEntitys.Count > 0)
            {
                var model = new PagedList<BSRolePageInfo>(EmitHelper.Map<BSRoleInfo, BSRolePageInfo>(roles.RoleEntitys), request.PageIndex, request.PageSize, roles.Total);
                return View("Index", model);
            }
            return View("Index"); 
        }
        [MenuItem("~/Authority/Index")]
        public ActionResult EditModules(int roleId, string roleName)
        {
            ViewBag.RoleId = roleId;
            ViewBag.RoleName = roleName;
            return View();
        }
        [HttpPost]
        public ActionResult UpdateRoleModuleRelationship()
        {
            int roleId = int.Parse(Request["roleId"]);
            List<int> moduleIds = new List<int>();
            List<BSRoleModuleInfo> list = new List<BSRoleModuleInfo>();
            if (!string.IsNullOrEmpty(Request["moduleIds"]))
            {
                moduleIds = Request["moduleIds"].Split(',').Select(n => int.Parse(n)).ToList();
                moduleIds.ForEach(n => list.Add(new BSRoleModuleInfo() { RoleID = roleId, ModuleID = n }));
            }

            RoleModuleDatas model = new RoleModuleDatas();
            model.RoleModules = list;
            model.RoleID = roleId;

            var response = HttpHelper.Post(Server + ServicePath.RoleWrite,
                JsonConvert.SerializeObject(
                new
                {
                    ActionName = "CreateBSRoleModules",
                    Pars =
                      new
                      {
                          roleModules = model
                      }
                }));
            if (response.IsSuccess)
            {
                CacheHelper.Remove<List<BSRoleModuleInfo>>(CacheKey.BSRoleModuleFull);
            }
            //更新RoleModule的缓存信息
            return RedirectToAction("Index", new { gridStage = Request.QueryString["gridStage"] });
        }

        public ActionResult GetAllModulesWithRole(int id)
        {
            List<JsTreeNode> result = CurCache.BSModuleFull.OrderBy(o => o.ParentID).ThenBy(o => o.ModuleOrder).Select(
               n => new JsTreeNode
               {
                   icon = n.ModuleIcon,
                   id = n.ID.ToString(),
                   parent = (n.ParentID == null || n.ParentID == 0) ? "#" : n.ParentID.ToString(),
                   text = n.ModuleName,
                   state = new State
                   {
                       opened = true,
                       disabled = false,
                       selected = false
                   }
               }
               ).ToList();

            var list = HttpHelper.Post<RoleModuleDatas>(Server + ServicePath.RoleRead,
                JsonConvert.SerializeObject(
                new
                {
                    ActionName = "RetrieveBSRoleModulesByRoleID",
                    Pars =
                      new
                      {
                          roleID = id
                      }
                }));
            if (null != list.RoleModules)
            {
                foreach (var item in list.RoleModules)
                {
                    foreach (var node in result)
                    {
                        if (item.ModuleID == int.Parse(node.id))
                        {
                            node.state.selected = true;
                            break;
                        }
                    }
                }
            }
            return Json(result);
        }

        [MenuItem("~/Authority/Index")]
        public ActionResult AddUserRoleRelationShip()
        {
            var Ids = Request["selectedUsers"];
            int roleId = int.Parse(Request["roleId"]);
            if (!string.IsNullOrEmpty(Ids))
            {
                List<string> selectedUserIds = Ids.Split(',').ToList();
                List<BSUserRoleInfo> list = new List<BSUserRoleInfo>();
                selectedUserIds.ForEach(n => list.Add(new BSUserRoleInfo() { RoleID = roleId, UserID = int.Parse(n) }));
                UserRoleDatas model = new UserRoleDatas();
                model.UserRoles = list;
                model.RoleID = roleId;

                var response = HttpHelper.Post(Server + ServicePath.UserWrite,
                    JsonConvert.SerializeObject(
                    new
                    {
                        ActionName = "CreateBSUserRoles",
                        Pars =
                          new
                          {
                              UserRoles = model
                          }
                    }));
                if (response.IsSuccess)
                {
                    //    AddOperationLog(
                    //BaseSystem.Model.BusinessTarget.Authority,
                    //BaseSystem.Model.BusinessAction.Edit,
                    //roleId,
                    //string.Format("用户[{0}]编辑角色{1}的用户权限", UserSession.Current.UserCode, result.DataContext.ROLE_CODE));
                }
            }
            ViewBag.RoleId = roleId;
            ViewBag.RoleName = Request["roleName"];
            return RedirectToAction("EditUsers", new { RoleId = roleId, RoleName = ViewBag.RoleName });
        }


        [MenuItem("~/Authority/Index")]
        public ActionResult RemoveUsersUnderRole()
        {
            var Ids = Request["selectedUsers"];
            int roleId = int.Parse(Request["roleId"]);
            if (!string.IsNullOrEmpty(Ids))
            {
                List<string> selectedUserIds = Ids.Split(',').ToList();
                List<int> models = new List<int>();
                selectedUserIds.ForEach(n => models.Add(int.Parse(n)));
                UserRoleDatas model = new UserRoleDatas();
                model.Users = models;
                model.RoleID = roleId;
                var response = HttpHelper.Post(Server + ServicePath.UserWrite,
                    JsonConvert.SerializeObject(
                    new
                    {
                        ActionName = "DeleteBSUserRoles",
                        Pars =
                          new
                          {
                              UserRoles = model
                          }
                    }));
                if (response.IsSuccess)
                {
                    //    AddOperationLog(
                    //BaseSystem.Model.BusinessTarget.Authority,
                    //BaseSystem.Model.BusinessAction.Edit,
                    //roleId,
                    //string.Format("用户[{0}]编辑角色{1}的用户权限", UserSession.Current.UserCode, result.DataContext.ROLE_CODE));
                }
            }
            ViewBag.RoleId = roleId;
            ViewBag.RoleName = Request["roleName"];
            return RedirectToAction("EditUsers", new { RoleId = roleId, RoleName = ViewBag.RoleName });
        }

        [MenuItem("~/Authority/Index")]
        public ActionResult EditUsers(int roleID, string roleName, BSUserPageInfo model)
        {

            ViewBag.RoleId = roleID;
            return QueryBsUser(new BSUserPageInfo() { PageIndex = (null != model) ? model.PageIndex : 1, RoleID = roleID },roleName);
        }
        public ActionResult QueryBsUser(BSUserPageInfo request,string roleName="")
        {
            //request.PageSize = PageSize;
            request.NotUnder = false;
            ViewBag.RoleName = roleName;
            UserDatas users = HttpHelper.Post<UserDatas>(Server + ServicePath.UserRead,
                    JsonConvert.SerializeObject(
                    new
                    {
                        ActionName = "RetrieveUsersByRole",
                        Pars =
                          new
                          {
                              user = EmitHelper.Map<BSUserPageInfo, BSUserInfo>(request),
                              roleid = request.RoleID,
                              notUnder = request.NotUnder,
                              page = EmitHelper.Map<BSUserPageInfo, PageInfo>(request)
                          }
                    }));
            if (null != users && null != users.UserEntitys && users.UserEntitys.Count > 0)
            {
                var model = new PagedList<BSUserPageInfo>(EmitHelper.Map<BSUserInfo, BSUserPageInfo>(users.UserEntitys), request.PageIndex, request.PageSize, users.Total);
                return View("EditUsers", model);
            }
            return View("EditUsers"); ;
        }

        [MenuItem("~/Authority/Index")]
        public ActionResult AddUsers(int roleID, string roleName, BSUserPageInfo model)
        {
            ViewBag.RoleId = roleID;
            ViewBag.RoleName = roleName;

DoKnow.CloudEdu.CMS.Host/Views/Authority/AddUsers.cshtml
@{
    ViewBag.Title = "添加用户";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="~/Assets/global/Plugins/jquery-1.11.0.min.js"></script>
<script type="text/javascript" src="@Url.Content("~/Scripts/My97DatePicker/WdatePicker.js")"></script>
@using Webdiyer.WebControls.Mvc;
@using DoKnow.CloudEdu.CMS.Host.Models;
@using DoKnow.CloudEdu.Common.Enums;
@model Webdiyer.WebControls.Mvc.PagedList<BSUserPageInfo>
<!-- BEGIN PAGE HEADER-->
@Html.Partial("_PageHeader", new PageHeader() { Title = "添加用户", Urls = new Dictionary<string, string>() { { "权限管理", "/Authority/Index" }, { "用户管理", "/Authority/EditUsers" }, { "添加用户", "#" } } })
<!-- END PAGE HEADER -->
<div>
    @using (Html.BeginForm("GetUsersNotUnderRoleId", "Authority", new RouteValueDictionary { { "pageIndex", "" } }, FormMethod.Get))
    {

        <div id="searchContatiner" action="#" class="form-horizontal">
            <div class="form-body">
                <div class="row">
                    <div class="col-md-3">
                        <div class="form-group">
                            <label class="control-label col-md-3">角色</label>
                            <div class="col-md-9">
                                <input type="text" name="RoleName" class="form-control input-small" value="@ViewBag.RoleName" readonly="readonly">
                                <input type="hidden" name="roleId" value="@ViewBag.RoleId" />
                                <span class="help-block">
                                </span>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            <label class="control-label col-md-3">编码</label>
                            <div class="col-md-8">
                                <input type="text" name="Code" class="form-control input-small" id="txtCode">
                                <span class="help-block">
                                </span>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            <label class="control-label col-md-3">真实姓名</label>
                            <div class="col-md-8">
                                <input type="text" name="Name" class="form-control input-small" id="txtName">
                                <span class="help-block">
                                </span>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn red">                    查询                </button>
                        <button type="reset" class="btn default">清除</button>
                    </div>
                </div>
            </div>
        </div>

    }
</div>
<form id="user" action="@Url.Action("AddUserRoleRelationShip")">
    <input type="hidden" name="roleId" value="@ViewBag.RoleId" />
    <input type="hidden" name="roleName" value="@ViewBag.RoleName" />
    <div class="portlet box purple">
        <div class="portlet-title">
            <div class="caption">
                <i class="fa fa-cogs"></i>
            </div>
            <div class="actions">
                <input type="submit" id="btnRemove" class="btn green" value="添加" />
                <a href="@Url.Action("EditUsers", "Authority", new { RoleId = @ViewBag.RoleId, RoleName = @ViewBag.RoleName })" class="btn green">取消</a>
            </div>
        </div>
        <div style="background-color: #ffffff; border: 1px solid #eaeaea; border-radius: 5px; line-height: 24px; padding: 8px; position: relative; font-size: 14px; overflow-x: auto;">
            <table class="table table-striped table-hover table-bordered" style=" max-width: 1600px;">
                <thead>
                    <tr>
                        <th>操作</th>
                        <th>用户编号</th>
                        <th>实名</th>
                        <th>昵称</th>
                        <th>手机号</th>
                        <th>用户类型</th>
                        <th>状态</th>
                        <th>创建时间</th>
                        <th>最后修改时间</th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model != null)
                    {
                        foreach (var item in Model)
                        {
                            <tr>
                                <td style="width: 100px;">
                                    <input type="checkbox" name="selectedUsers" value="@item.ID" class="form-control">
                                </td>
                                <td>@item.Code</td>
                                <td>@item.RealName</td>
                                <td>@item.NickName</td>
                                <td>@item.Mobile</td>
                                <td>@EnumHelper.GetDescription(typeof(EnumHelper.UserCategory), item.Category)</td>
                                <td>@EnumHelper.GetDescription(typeof(EnumHelper.CommonStatus), item.Status)</td>
                                <td>
                                    @if (item.CreateTime.ToString("yyyy-MM-dd") != "1990-01-01")
                                    { @item.CreateTime.ToString()}
                                </td>
                                <td>
                                    @if (item.ModifyTime.ToString("yyyy-MM-dd") != "1990-01-01")
                                    { @item.ModifyTime.ToString("")}
                                </td>
                            </tr>
                        }
                        <tr>
                            <td colspan="14" class="pager-footer">
                                @Html.Pager(Model, new PagerOptions
                       {
                           PageIndexParameterName = "PageIndex",
                           ShowPageIndexBox = false,
                           FirstPageText = "首页",
                           PrevPageText = "上一页",
                           NextPageText = "下一页",
                           LastPageText = "末页",
                           ShowGoButton = false,

                       })
                                <div style="float: right;">
                                    共 @Model.TotalPageCount 页 @Model.TotalItemCount 条记录，当前为第 @Model.CurrentPageIndex 页
                                </div>
                            </td>
                        </tr>
                    }
                    else
                    {
                        <tr>
                            <td colspan="14">@ViewBag.Msg</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</form>
<style type="text/css">
    .ProduceTab {
        width: 100%;
        background: none repeat scroll 0 0 #F2F2F2;
    }

        .ProduceTab input {
            width: 130px;
        }
</style>
<script type="text/javascript">
    function GetDateDiff(startDate, endDate) {
        var startTime = new Date(Date.parse(startDate.replace(/-/g, "/"))).getTime();
        var endTime = new Date(Date.parse(endDate.replace(/-/g, "/"))).getTime();
        var dates = Math.abs((startTime - endTime)) / (1000 * 60 * 60 * 24);
        return dates;
    }
    function CliExport() {
        if ($("#ORDER_BEGIN_TIME").val() == "" || $("#ORDER_END_TIME").val() == "") {
            alert("请选择创建订单时间！"); return false;
        }
        else {
            var startDate = $("#ORDER_BEGIN_TIME").val();
            var endDate = $("#ORDER_END_TIME").val();
            var days = GetDateDiff(startDate, endDate);
            if (days > 7) {
                alert("单次查询最大时间跨度为7天！");
                return false;
            }
        }
        var QueryProduce = {};
        QueryProduce["ORDER_CODE"] = $("#ORDER_CODE").val();//订单号
        QueryProduce["STATUS"] = $("#status").val() == "" ? "0" : $("#STATUS").val();//生产单状态
        QueryProduce["ORDER_BEGIN_TIME"] = $("#ORDER_BEGIN_TIME").val();//打版开始时间
        QueryProduce["ORDER_END_TIME"] = $("#ORDER_END_TIME").val();//打版结束时间
        var link = "/PreProduce/Export?QueryProduce=" + JSON.stringify(QueryProduce);
        window.open(link);
    }
</script>

DoKnow.CloudEdu.CMS.Host/Views/Authority/EditModules.cshtml
@{
    ViewBag.Title = "模块权限";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="~/Assets/global/Plugins/jquery-1.11.0.min.js"></script>
@section scripts{
    <script src="~/Assets/global/Plugins/jsTree/dist/jstree.js"></script>
    <script>
        $(
        function () {
            $.ajax({
                url: "/Authority/GetAllModulesWithRole/@ViewBag.RoleId",
            type: "post",
            dataType: "json",
            success: function (data) {
                $("#module_tree").jstree({
                    "core": {
                        'data': data
                    },
                    "plugins": ["checkbox", "sort", "search"]
                });
                $('#module_tree').on("changed.jstree", function (e, data) {
                    $('#moduleIds').val($('#module_tree').jstree(true).get_bottom_selected(false));
                });

            },
        });

        $('#module_tree').on("ready.jstree", function (e, data) {
            $('#module_tree').jstree('close_all');
        });
        var to = false;
        $('#query').keyup(function () {
            if (to) { clearTimeout(to); }
            to = setTimeout(function () {
                var v = $('#query').val();
                $('#module_tree').jstree(true).search(v);
            }, 250);
        });
    }
    )
    </script>
}

<h3 class="page-title">
    权限管理 <small>模块管理</small>
</h3>
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <i class="fa fa-home"></i>
            <a href="index.html">首页</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <a href="@Url.Action("Index", "Authority")">权限管理</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <a href="#">管理</a>
        </li>
    </ul>
    <div class="page-toolbar">
        <div class="btn-group pull-right">
        </div>
    </div>
</div>
<div class="portlet box purple">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-cogs"></i>
        </div>
        <div class="tools">
            <a href="javascript:;" class="collapse"></a>
        </div>
        <div class="actions">
            <a class="btn green" href="@Url.Action("Index", new { RoleCode = Request.QueryString["RoleCode"], RoleName = @Request.QueryString["RoleName"] })"><i class="fa  fa-mail-reply"></i>返回</a>
        </div>
    </div>
    <div class="portlet-body form">

        <form id="menuCreate" action="@Url.Action("UpdateRoleModuleRelationship")" method="post" class="form-horizontal">
            <div class="form-body">
                <input type="hidden" value="@ViewBag.RoleId" id="roleId" name="roleId" />
                <div class="form-group">
                    <label class="col-md-3 control-label">角色名称&nbsp;&nbsp;</label>
                    <div class="col-md-4">
                        <input type="text" id="roleName" name="roleName" class="form-control" readonly="readonly" value="@Request.QueryString["DispRoleName"]">
                        <span class="help-block"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="row">
                        <label class="col-md-3 control-label">角色权限操作&nbsp;&nbsp;</label>
                        <div class="col-md-4">
                            <input type="text" id="query" class="form-control" placeholder="组织搜索条件">
                            <input type="hidden" id="moduleIds" value="" name="moduleIds" />
                        </div>
                    </div>
                    <div class="col-md-3"></div>
                    <div id="module_tree" class="col-md-4">
                    </div>
                </div>
                @* <div class="row">*@
            </div>
            <div class="form-actions"><div class="col-md-offset-3 col-md-9">
                    <button type="submit" class="btn red">确定</button>
                    <a href="@Url.Action("Index", new { RoleCode = Request.QueryString["RoleCode"], RoleName = @Request.QueryString["RoleName"] })" class="btn default">取消</a>
                </div>
                @* </div>*@
            </div>
        </form>

    </div>
</div>

DoKnow.CloudEdu.CMS.Host/Views/Authority/EditUsers.cshtml
@{
    ViewBag.Title = "用户权限";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="~/Assets/global/Plugins/jquery-1.11.0.min.js"></script>
<script type="text/javascript" src="@Url.Content("~/Scripts/My97DatePicker/WdatePicker.js")"></script>
@using Webdiyer.WebControls.Mvc;
@using DoKnow.CloudEdu.CMS.Host.Models;
@using DoKnow.CloudEdu.Common.Enums;
@model Webdiyer.WebControls.Mvc.PagedList<BSUserPageInfo>
<!-- BEGIN PAGE HEADER-->
@Html.Partial("_PageHeader", new PageHeader() { Title = "用户权限", Urls = new Dictionary<string, string>() { { "权限管理", "/Authority/Index" }, { "用户权限", "#" } } })
<!-- END PAGE HEADER -->
<div>
    @using (Html.BeginForm("QueryBsUser", "Authority", new RouteValueDictionary { { "pageIndex", "" } }, FormMethod.Get))
    {

        <div id="searchContatiner" action="#" class="form-horizontal">
            <div class="form-body">
                <div class="row">
                    <div class="col-md-3">
                        <div class="form-group">
                            <label class="control-label col-md-3">角色</label>
                            <div class="col-md-8">
                                <input type="text" name="roleName" class="form-control input-small" value="@Request.QueryString["DispRoleName"]" readonly="readonly">
                                <input type="hidden" name="roleId" value="@ViewBag.RoleId" />
                                <span class="help-block">
                                </span>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            <label class="control-label col-md-3">用户编码</label>
                            <div class="col-md-8">
                                <input type="text" name="code" class="form-control input-small" value="@Request.QueryString["code"]" id="code">
                                <span class="help-block">
                                </span>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            <label class="control-label col-md-3">真实姓名</label>
                            <div class="col-md-8">
                                <input type="text" name="RealName" class="form-control input-small" value="@Request.QueryString["RealName"]" id="txtRealName">
                                <span class="help-block">
                                </span>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <button type="submit" class="btn green">查询</button>
                        <button type="reset" class="btn default">清除</button>
                    </div>
                </div>
            </div>
        </div>

    }
</div>
<form id="user" action="@Url.Action("RemoveUsersUnderRole")">
    <input type="hidden" name="roleId" value="@ViewBag.RoleId" />
    <input type="hidden" name="roleName" value="@ViewBag.RoleName" />
    <div class="portlet box purple">
        <div class="portlet-title">
            <div class="actions">
                <a href="@Url.Action("AddUsers", "Authority", new { RoleId = @ViewBag.RoleId, RoleName = @ViewBag.RoleName })" class="btn green"><i class="fa fa-plus"></i>添加</a>
                <button type="submit" id="btnRemove" class="red btn" value=""><i class="fa fa-trash-o"></i>移除</button>
                <a href="@Url.Action("Index", new {RoleCode = Request.QueryString["RoleCode"], RoleName = @Request.QueryString["RoleName"] })" class="btn green"><i class="fa fa-reply"></i>返回</a>
            </div>
        </div>
        <div style="background-color: #ffffff; border: 1px solid #eaeaea; border-radius: 5px; line-height: 24px; padding: 8px; position: relative; font-size: 14px; overflow-x: auto;">
            <table class="table table-striped table-hover table-bordered" style=" max-width: 1600px;">
                <thead>
                    <tr>
                        <th>操作</th>
                        <th>用户编号</th>
                        <th>实名</th>
                        <th>昵称</th>
                        <th>手机号</th>
                        <th>用户类型</th>
                        <th>状态</th>
                        <th>创建时间</th>
                        <th>最后修改时间</th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model != null)
                    {
                        foreach (var item in Model)
                        {
                            <tr>
                                <td style="width: 100px;">
                                    <input type="checkbox" name="selectedUsers" value="@item.ID" class="form-control">
                                </td>
                                <td>@item.Code</td>
                                <td>@item.RealName</td>
                                <td>@item.NickName</td>
                                <td>@item.Mobile</td>
                                <td>@EnumHelper.GetDescription(typeof(EnumHelper.UserCategory), item.Category)</td>
                                <td>@EnumHelper.GetDescription(typeof(EnumHelper.CommonStatus), item.Status)</td>
                                <td>
                                    @if (item.CreateTime.ToString("yyyy-MM-dd") != "1990-01-01")
                                    { @item.CreateTime.ToString()}
                                </td>
                                <td>
                                    @if (item.ModifyTime.ToString("yyyy-MM-dd") != "1990-01-01")
                                    { @item.ModifyTime.ToString("")}
                                </td>
                            </tr>
                        }
                        <tr>
                            <td colspan="14" class="pager-footer">
                                @Html.Pager(Model, new PagerOptions
                       {
                           PageIndexParameterName = "PageIndex",
                           ShowPageIndexBox = false,
                           FirstPageText = "首页",
                           PrevPageText = "上一页",
                           NextPageText = "下一页",
                           LastPageText = "末页",
                           ShowGoButton = false,

                       })
                                <div style="float: right;">
                                    共 @Model.TotalPageCount 页 @Model.TotalItemCount 条记录，当前为第 @Model.CurrentPageIndex 页
                                </div>
                            </td>
                        </tr>
                    }
                    else
                    {
                        <tr>
                            <td colspan="14">@ViewBag.Msg</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</form>
<style type="text/css">
    .ProduceTab {
        width: 100%;
        background: none repeat scroll 0 0 #F2F2F2;
    }

        .ProduceTab input {
            width: 130px;
        }
</style>
<script type="text/javascript">
    function GetDateDiff(startDate, endDate) {
        var startTime = new Date(Date.parse(startDate.replace(/-/g, "/"))).getTime();
        var endTime = new Date(Date.parse(endDate.replace(/-/g, "/"))).getTime();
        var dates = Math.abs((startTime - endTime)) / (1000 * 60 * 60 * 24);
        return dates;
    }
    function CliExport() {
        if ($("#ORDER_BEGIN_TIME").val() == "" || $("#ORDER_END_TIME").val() == "") {
            alert("请选择创建订单时间！"); return false;
        }
        else {
            var startDate = $("#ORDER_BEGIN_TIME").val();
            var endDate = $("#ORDER_END_TIME").val();
            var days = GetDateDiff(startDate, endDate);
            if (days > 7) {
                alert("单次查询最大时间跨度为7天！");
                return false;
            }
        }
        var QueryProduce = {};
        QueryProduce["ORDER_CODE"] = $("#ORDER_CODE").val();//订单号
        QueryProduce["STATUS"] = $("#status").val() == "" ? "0" : $("#STATUS").val();//生产单状态
        QueryProduce["ORDER_BEGIN_TIME"] = $("#ORDER_BEGIN_TIME").val();//打版开始时间
        QueryProduce["ORDER_END_TIME"] = $("#ORDER_END_TIME").val();//打版结束时间
        var link = "/PreProduce/Export?QueryProduce=" + JSON.stringify(QueryProduce);
        window.open(link);
    }
</script>