DoKnow.CloudEdu.CMS.Host/Controllers/BsRoleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DoKnow.CloudEdu.CMS.Host.Models;
using DoKnow.CloudEdu.Common.Attrs;
using DoKnow.CloudEdu.Common.Consts;
using DoKnow.CloudEdu.Common.Enums;
using DoKnow.CloudEdu.DataContract.Model.Base;
using DoKnow.Common.Utility;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Webdiyer.WebControls.Mvc;

namespace DoKnow.CloudEdu.CMS.Host.Controllers
{
    public class BsRoleController : BaseController
    {
        //
        // GET: /BsRole/

        public ActionResult Index(BSRolePageInfo request)
        {
            if (null != TempData["Msg"])
            {
                ViewBag.Msg = TempData["Msg"].ToString();
            }
            return QueryBsRole(request);
        }
        [MenuItem("~/BsRole/Index")]
        public ActionResult QueryBsRole(BSRolePageInfo request)
        {
            RoleDatas roles = HttpHelper.Post<RoleDatas>(Server + ServicePath.RoleRead,
                JsonConvert.SerializeObject(
                new
                {
                    ActionName = "RetrieveRoles",
                    Pars =
                      new
                      {
                          role = EmitHelper.Map<BSRolePageInfo, BSRoleInfo>(request),
                          page = EmitHelper.Map<BSRolePageInfo, PageInfo>(request)
                      }
                }));
            if (null != roles && null != roles.RoleEntitys && roles.RoleEntitys.Count > 0)
            {
                var model = new PagedList<BSRolePageInfo>(EmitHelper.Map<BSRoleInfo, BSRolePageInfo>(roles.RoleEntitys), request.PageIndex, request.PageSize, roles.Total);
                return View("Index", model);
            }
            return View("Index"); 
        }
        [MenuItem("~/BsRole/Index")]
        public ActionResult Edit(int id,string roleCode,string roleName)
        {
            var model = HttpHelper.Post<BSRoleInfo>(Server + ServicePath.RoleRead,
                    JsonConvert.SerializeObject(
                    new
                    {
                        ActionName = "RetrieveRole",
                        Pars =
                          new
                          {
                              role = new BSRoleInfo() { ID = id }
                          }
                    }));
            if (model != null)
            {
                ViewBag.ComStatus = EnumHelper.GetSelectList<EnumHelper.CommonStatus>(model.Status.ToString());
                return View("Edit", model);
            }
            else
            {
                TempData["Msg"] = "该角色已不存在！";
                return RedirectToAction("Index", new { RoleCode = roleCode, RoleName = roleName });
            }
        }
        [MenuItem("~/BsRole/Index")]
        public ActionResult Add()
        {
            ViewBag.ComStatus = EnumHelper.GetSelectList<EnumHelper.CommonStatus>();
            return View("Add", new BSRoleInfo());
        }
        /// <summary>
        /// 编辑
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [MenuItem("~/BsRole/Index")]
        [HttpPost]
        public ActionResult AddSave(BSRoleInfo model)
        {
            //var managerClient = new BsRoleManagerClient();
            model.Creator = model.Modifier = CurrentUser.UserEntity.Code;
            model.CreateTime = model.ModifyTime = System.DateTime.Now;
            //model.STATUS = (int)EnumHelper.CommonStatus.Active;
            var response = HttpHelper.Post(Server + ServicePath.RoleWrite,
                    JsonConvert.SerializeObject(
                    new
                    {
                        ActionName = "CreateRole",
                        Pars =
                          new
                          {
                              role = model
                          }
                    }, new IsoDateTimeConverter() { DateTimeFormat = "yyyy-MM-dd HH:mm:ss" }));
            if (!response.IsSuccess)
            {
                ViewBag.ComStatus = EnumHelper.GetSelectList<EnumHelper.CommonStatus>(model.Status.ToString());
                ViewBag.ErrMsg = string.IsNullOrEmpty(response.ErrMsg) ? string.Empty : (response.ErrMsg + ",") + "新增失败！";
                return View("Add", model);
            }
            else
            {
                TempData["Msg"] = "新增成功！";
                return RedirectToAction("Index");
            }
        }
        /// <summary>
        /// 编辑
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [MenuItem("~/BsRole/Index")]
        [HttpPost]
        public ActionResult EditSave(BSRoleInfo model)
        {
            model.Modifier = CurrentUser.UserEntity.Code;
            model.ModifyTime = System.DateTime.Now;
            //model.STATUS = (int)EnumHelper.CommonStatus.Active;
            var response = HttpHelper.Post(Server + ServicePath.RoleRead,
                    JsonConvert.SerializeObject(
                    new
                    {
                        ActionName = "UpdateRole",
                        Pars =
                          new
                          {
                              role = model
                          }
                    }, new IsoDateTimeConverter() { DateTimeFormat = "yyyy-MM-dd HH:mm:ss" }));
            if (!response.IsSuccess)
            {
                ViewBag.ErrMsg = string.IsNullOrEmpty(response.ErrMsg) ? string.Empty : (response.ErrMsg + ",") + "编辑失败！";
                ViewBag.ComStatus = EnumHelper.GetSelectList<EnumHelper.CommonStatus>(model.Status.ToString());
                return View("Edit", model);
            }
            else
            {
                TempData["Msg"] = "编辑成功！";
                return RedirectToAction("Index");
            }
        }

        [MenuItem("~/BsRole/Index")]
        public ActionResult Delete(int id)
        {
            var response = HttpHelper.Post(Server + ServicePath.RoleWrite,
                JsonConvert.SerializeObject(
                new
                {
                    ActionName = "DeleteRole",
                    Pars =
                      new
                      {
                          ID = id
                      }
                }));
            if (response.IsSuccess)
            {
                TempData["Msg"] = "删除成功！";
                return RedirectToAction("Index");
            }
            else
            {
                TempData["Msg"] = string.IsNullOrEmpty(response.ErrMsg) ? string.Empty : (response.ErrMsg + ",") + "删除失败！";
                return RedirectToAction("Index");
            }
        }
        public ActionResult GetRoleStatus()
        {
            var status = EnumHelper.GetList(typeof(EnumHelper.CommonStatus));
            var result = Json(status);
            return result;
        }
    }
}

DoKnow.CloudEdu.CMS.Host/Views/BsRole/Add.cshtml
@{
    ViewBag.Title = "新增角色";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="~/Assets/global/Plugins/jquery-1.11.0.min.js"></script>
@using DoKnow.CloudEdu.CMS.Host.Models;
@using DoKnow.CloudEdu.Common.Enums;
@model DoKnow.CloudEdu.DataContract.Model.Base.BSRoleInfo
<!-- BEGIN PAGE HEADER-->
@Html.Partial("_PageHeader", new PageHeader() { Title = "新增角色", Urls = new Dictionary<string, string>() { { "角色管理", "/BsRole/Index" }, { "新增角色", "#" } } })
<!-- END PAGE HEADER -->

<div class="portlet box purple">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-cogs"></i>
        </div>
        <div class="tools">
            <a href="javascript:;" class="collapse"></a>
        </div>
        <div class="actions">
            <a class="btn green" href="@Url.Action("Index", new { RoleCode = Request.QueryString["RoleCode"], RoleName = @Request.QueryString["RoleName"] })"><i class="fa  fa-mail-reply">返回</i> </a>
        </div>
    </div>
    <div class="portlet-body form">
        <!-- BEGIN FORM-->
        <form id="bsUserAdd" action="@Url.Action("AddSave")" method="post" class="form-horizontal">
            <div class="form-body">
                <div class="form-group">
                    <label class="col-md-3 control-label">

                    </label>
                    <div class="col-md-4 control-label">
                        <span class="required" aria-required="true">
                            @ViewBag.ErrMsg
                        </span>

                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label">
                        角色名称
                    </label>
                    <div class="col-md-4">
                        <input type="text" id="txtRoleName" name="RoleName" value="@Model.RoleName" class="form-control" placeholder="请输入角色名称">
                        <span class="help-block"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label">
                        状态
                    </label>
                    <div class="col-md-4">
                        @Html.DropDownList("Status", ViewBag.ComStatus as SelectList, new { @class = "form-control input-medium" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label">
                        备注&nbsp;&nbsp;&nbsp;
                    </label>
                    <div class="col-md-4">
                        <textarea style="height: 100px;" id="txtRemark" name="Remark" class="form-control" placeholder="请输入备注">@Model.Remark</textarea>
                        <span class="help-block"></span>
                    </div>
                </div>
            </div>
            <div class="form-actions">
                <div class="row">
                    <div class="col-md-offset-3 col-md-9">
                        <button type="submit" class="btn red" id="sure">确定</button>
                        <a href="@Url.Action("Index", new { RoleCode = Request.QueryString["RoleCode"], RoleName = @Request.QueryString["RoleName"] })" class="btn default">取消</a>
                    </div>
                </div>
            </div>
        </form>
        <!-- END FORM-->
    </div>
</div>
@section scripts{
    <script src="~/Assets/global/Plugins/jquery-validation/jquery.validate.min.js"></script>
    <script src="~/Assets/global/Plugins/jquery-validation/additional-methods.min.js"></script>
    <script src="~/Assets/global/Plugins/jsTree/dist/jstree.min.js"></script>
    <script type="text/javascript">
        function pageReady() {
            //获取类型
            var oldType = $("#oldType").val();
            $.ajax({
                url: "/BsUser/GetUserCategroy",
                type: "post",
                data: '',
                success: function (data) {
                    $("#userType").append(BindTypeOption(data));
                    $("#userType").find("option[value='" + oldType + "']").attr("selected", "selected");
                }
            });
            var form1 = $('#bsUserAdd');
            var error1 = $('.alert-danger', form1);
            var success1 = $('.alert-success', form1);

            form1.validate({
                errorElement: 'span',
                errorClass: 'help-block help-block-error',
                focusInvalid: false,
                ignore: "",
                messages: {
                    Mobile: {
                        required: "手机必填",
                        byteMaxLength: "名称要小于50个字节(一个中文字算2个字节)"
                    },
                    Remark: {
                        byteMaxLength: "备注要小于100个字节(一个中文字算2个字节)"
                    }
                },
                rules:
                {
                    Mobile: {
                        required: true,
                        byteMaxLength: 15
                    },
                    Remark: {
                        byteMaxLength: 100
                    }
                },

                invalidHandler: function (event, validator) {
                    success1.hide();
                    error1.show();
                    Metronic.scrollTo(error1, -200);
                },

                highlight: function (element) {
                    $(element).closest('.form-group').addClass('has-error');
                },

                unhighlight: function (element) {
                    $(element).closest('.form-group').removeClass('has-error');
                },

                success: function (label) {
                    label.closest('.form-group').removeClass('has-error');
                },

                submitHandler: function (form) {
                    success1.show();
                    error1.hide();
                    form.submit();
                }
            });
        }
        //生成类型下拉
        function BindTypeOption(objArray) {
            var optionList = "";
            if (objArray != null) {
                for (var i = 0; i < objArray.length; i++) {
                    var obj = objArray[i];
                    optionList += "<option id=\"" + obj.Key + "\" value=\"" + obj.Value + "\">" + obj.Key + "</option>";
                }
            }
            return optionList;
        }
        function CheckExist(setValue) {
            if ($("#userType").val() == "@((int)EnumHelper.UserCategory.Employee)" && ($("#oldStaffID").val() != $("#FACTORY_STAFF_ID").val())) {
                var checkResult = true;
                $.ajax({
                    url: "/BsUser/CheckStaffID?ID=" + $("#FACTORY_STAFF_ID").val(),
                    type: "post",
                    dataType: "json",
                    async: false,
                    success: function (data) {
                        checkResult = data.IsSuccess;
                        if (checkResult == false) {
                            alert("该工厂员工ID不存在！");
                            return false;
                        } else {
                            if (setValue) {
                                $("#txtCode").val(data.Employee.CODE);
                                $("#txtName").val(data.Employee.NAME);
                                $("#txtMOBILE").val(data.Employee.MOBILE);
                            } else {
                                checkResult = confirm("该员工为：" + data.Employee.NAME + "(" + data.Employee.CODE + "),请确认关联？");
                            };
                        }
                    }
                });
                return checkResult;
            }
        }
        $("#sure").click(function () {
            var result = CheckExist(false);
            return result;
        });

        $("#userType").change(function () {

            //console.log($("#userType").val())
            if ($("#userType").val() != "@((int)EnumHelper.UserCategory.Employee)") {
                document.getElementById("divStaff").style.display = "none";
            }
            else {
                document.getElementById("divStaff").style.display = "";
            }
        });
        $("#FACTORY_STAFF_ID").change(function () {
            CheckExist(true);
        });
    </script>
}

DoKnow.CloudEdu.CMS.Host/Views/BsRole/Index.cshtml
@{
    ViewBag.Title = "角色管理";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="~/Assets/global/Plugins/jquery-1.11.0.min.js"></script>
<script type="text/javascript" src="@Url.Content("~/Scripts/My97DatePicker/WdatePicker.js")"></script>
@using Webdiyer.WebControls.Mvc;
@using DoKnow.CloudEdu.CMS.Host.Models;
@using DoKnow.CloudEdu.Common.Enums;
@model Webdiyer.WebControls.Mvc.PagedList<BSRolePageInfo>
<!-- BEGIN PAGE HEADER-->
@Html.Partial("_PageHeader", new PageHeader() { Title = "角色管理", Urls = new Dictionary<string, string>() { { "角色管理", "#" } } })
<!-- END PAGE HEADER -->
<div>
    @using (Html.BeginForm("QueryByRole", "BsRole", new RouteValueDictionary { { "pageIndex", "" } }, FormMethod.Get))
    {

        <div id="searchContatiner" action="#" class="form-horizontal">
            <div class="form-body">
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="control-label col-md-3">角色编号</label>
                            <div class="col-md-6">
                                <input type="text" id="txtCODE" class="form-control input-medium" name="RoleCode" value="@Request.QueryString["RoleCode"]" />
                                <span class="help-block"></span>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="control-label col-md-3">角色名称</label>
                            <div class="col-md-6">
                                <input type="text" id="txtName" class="form-control input-medium" name="RoleName" value="@Request.QueryString["RoleName"]" />
                                <span class="help-block"></span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="col-md-3">
                            <div class="btn-group-solid">
                                <button type="submit" class="btn btn-primary btn-block green">查询</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    }
</div>
<div class="portlet box purple">
    <div class="portlet-title">
        <div class="actions">
            <a href="@Url.Action("Add")" class="btn green"><i class="fa fa-plus"></i>添加</a>
        </div>
    </div>
    <div style="background-color: #ffffff; border: 1px solid #eaeaea; border-radius: 5px; line-height: 24px; padding: 8px; position: relative; font-size: 14px; overflow-x: auto;">
        <table class="table table-striped table-hover table-bordered" style=" max-width: 1600px;">
            <thead>
                <tr>
                    <th>操作</th>
                    <th>角色编号</th>
                    <th>角色名称</th>
                    <th>备注</th>
                    <th>状态</th>
                    <th>创建时间</th>
                    <th>最后修改时间</th>
                </tr>
            </thead>
            <tbody>
                @if (Model != null)
                {
                    foreach (var item in Model)
                    {
                        <tr>
                            <td style="width: 150px;">
                                <a href="@Url.Action("Edit", new { ID = item.ID, RoleCode = Request.QueryString["RoleCode"], RoleName = @Request.QueryString["RoleName"] })" class="btn btn-sm green"><i class="fa fa-edit" style="margin: 0px;">编辑</i></a>
                                <a onclick="confirmDel('@Url.Action("Delete",new { id = item.ID, RoleCode = Request.QueryString["RoleCode"], RoleName = @Request.QueryString["RoleName"] })')" href="javascript:void(0)" class="btn btn-sm green"><i class="fa fa-remove" style="margin: 0px;">删除</i></a>
                            </td>
                            <td>@item.RoleCode</td>
                            <td>@item.RoleName</td>
                            <td>@item.Remark</td>
                            <td>@EnumHelper.GetDescription(typeof(EnumHelper.CommonStatus), item.Status)</td>
                            <td>
                                @if (item.CreateTime.ToString("yyyy-MM-dd") != "1990-01-01")
                                { @item.CreateTime.ToString()}
                            </td>
                            <td>
                                @if (item.ModifyTime.ToString("yyyy-MM-dd") != "1990-01-01")
                                { @item.ModifyTime.ToString("")}
                            </td>
                        </tr>
                    }
                    <tr>
                        <td colspan="14" class="pager-footer">
                            @Html.Pager(Model, new PagerOptions
                       {
                           PageIndexParameterName = "PageIndex",
                           ShowPageIndexBox = false,
                           FirstPageText = "首页",
                           PrevPageText = "上一页",
                           NextPageText = "下一页",
                           LastPageText = "末页",
                           ShowGoButton = false,

                       })
                            <div style="float: right;">
                                共 @Model.TotalPageCount 页 @Model.TotalItemCount 条记录，当前为第 @Model.CurrentPageIndex 页
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>
<style type="text/css">
    .ProduceTab {
        width: 100%;
        background: none repeat scroll 0 0 #F2F2F2;
    }

        .ProduceTab input {
            width: 130px;
        }
</style>
<script type="text/javascript">
    function GetDateDiff(startDate, endDate) {
        var startTime = new Date(Date.parse(startDate.replace(/-/g, "/"))).getTime();
        var endTime = new Date(Date.parse(endDate.replace(/-/g, "/"))).getTime();
        var dates = Math.abs((startTime - endTime)) / (1000 * 60 * 60 * 24);
        return dates;
    }
    function CliExport() {
        if ($("#ORDER_BEGIN_TIME").val() == "" || $("#ORDER_END_TIME").val() == "") {
            alert("请选择创建订单时间！"); return false;
        }
        else {
            var startDate = $("#ORDER_BEGIN_TIME").val();
            var endDate = $("#ORDER_END_TIME").val();
            var days = GetDateDiff(startDate, endDate);
            if (days > 7) {
                alert("单次查询最大时间跨度为7天！");
                return false;
            }
        }
        var QueryProduce = {};
        QueryProduce["ORDER_CODE"] = $("#ORDER_CODE").val();//订单号
        QueryProduce["STATUS"] = $("#status").val() == "" ? "0" : $("#STATUS").val();//生产单状态
        QueryProduce["ORDER_BEGIN_TIME"] = $("#ORDER_BEGIN_TIME").val();//打版开始时间
        QueryProduce["ORDER_END_TIME"] = $("#ORDER_END_TIME").val();//打版结束时间
        var link = "/PreProduce/Export?QueryProduce=" + JSON.stringify(QueryProduce);
        window.open(link);
    }
</script>
<script src="~/assets/global/plugins/jquery-1.10.1.min.js"></script>
<script>
    $(function () {
        if ("@ViewBag.Msg" != "") {
            bootbox.alert({
                size: "middle",
                animate: false,
                closeButton: false,
                className: "green-control",
                message: "@ViewBag.Msg"
            })
            //bootbox.alert("@ViewBag.Msg");
        }
    });
    function confirmDel(url) {
        bootbox.confirm({
            size: "small",
            animate: false,
            closeButton: false,
            className: "green-control",
            message: "确定要删除" + name + "吗?",
            callback: function (result) {
                if (result === true) {
                    window.location.href = url
                }
            }
        });
    };
</script>